export const DRONE_SOCKET = 'DRONE_SOCKET';
export const DRONE_STATUS_SOCKET = 'DRONE_STATUS_SOCKET';
export const DRONE_STREAM_SOCKET = 'DRONE_STREAM_SOCKET';

export const DRONE_PORT = 8889;
export const DRONE_STATUS_PORT = 8890;
export const DRONE_STREAM_PORT = 11111;

export const DRONE_HOST = '192.168.10.1';
